development:
  adapter: postgresql
  encoding: unicode
  database: travel_mentor_development
  pool: 5
  username:
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: travel_mentor_test
  pool: 5
  username:
  password: 

